// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFLiG2ipJ8SnchOAlMcNfdxdsYtmW7eDQ',
    appId: '1:176594000368:web:68cb059c9878e7f8052535',
    messagingSenderId: '176594000368',
    projectId: 'expense-tracker-b6ec8',
    authDomain: 'expense-tracker-b6ec8.firebaseapp.com',
    storageBucket: 'expense-tracker-b6ec8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiOfYLk__r-B8wyoax6VtizmpFAk4XXiM',
    appId: '1:176594000368:android:fcd48e5357a84d78052535',
    messagingSenderId: '176594000368',
    projectId: 'expense-tracker-b6ec8',
    storageBucket: 'expense-tracker-b6ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCODZpWewkCfpuEixSsW1mG4W-FSkBGuVk',
    appId: '1:176594000368:ios:c2b69d5bf32f0037052535',
    messagingSenderId: '176594000368',
    projectId: 'expense-tracker-b6ec8',
    storageBucket: 'expense-tracker-b6ec8.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCODZpWewkCfpuEixSsW1mG4W-FSkBGuVk',
    appId: '1:176594000368:ios:c2b69d5bf32f0037052535',
    messagingSenderId: '176594000368',
    projectId: 'expense-tracker-b6ec8',
    storageBucket: 'expense-tracker-b6ec8.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFLiG2ipJ8SnchOAlMcNfdxdsYtmW7eDQ',
    appId: '1:176594000368:web:cb6fab4883ead192052535',
    messagingSenderId: '176594000368',
    projectId: 'expense-tracker-b6ec8',
    authDomain: 'expense-tracker-b6ec8.firebaseapp.com',
    storageBucket: 'expense-tracker-b6ec8.firebasestorage.app',
  );
}
